class Consts:
    PAD = 20
    BORDER = 10
    BUTTON_BORDER = 6
    CELL_SIZE = 40

    DISPLAY_WIDTH = 50
    DISPLAY_HEIGHT = 100
    DISPLAY_ON = -1
    DISPLAY_OFF = -2
    SEGMENT_WIDTH = 10
    SEGMENT_DELTA = 5
